import type { Metadata } from "next";
import { Roboto_Mono } from "next/font/google";
import "./globals.css";
import TanStackQueryProvider from "@/providers/TanStackQueryProvider";
import Layout from "./components/Layout";

const roboto = Roboto_Mono({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={roboto.className}>
      <body>
        <Layout>
          <TanStackQueryProvider>{children}</TanStackQueryProvider>
        </Layout>
      </body>
    </html>
  );
}
