import type { Metadata } from "next";
import { Roboto_Mono } from "next/font/google";
import "./globals.css";
import TanStackQueryProvider from "@/providers/TanStackQueryProvider";
import Layout from "./components/Layout";
import StyledComponentsRegistry from "@/libs/registry";
import StoreProvider from "@/providers/StoreProvider";

const roboto = Roboto_Mono({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
});
// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export const metadata: Metadata = {
  title: "Template builder",
  description:
    "Welcome to the project I'm most proud of — lets you build, customize web page easily.",
  keywords: [
    "Pritakpol",
    "Web Developer",
    "Frontend Developer",
    "Full-Stack Developer",
    "React",
    "Next.js",
    "Portfolio",
    "TypeScript",
    "JavaScript",
  ],
  authors: [{ name: "Pritakpol", url: "https://personal-gan-web.vercel.app" }],
  creator: "Pritakpol",
  openGraph: {
    title: "Pritakpol's Portfolio",
    description:
      "Welcome to the project I'm most proud of — lets you build, customize web page easily.",
    url: "https://my-template-builder.vercel.app/",
    siteName: "Pritakpol Portfolio",
    images: [
      {
        url: "https://drive.google.com/file/d/1Hj3W_UaNdFgzJpiJelJ3e_SCg8if75hc/view?usp=sharing", // Replace with your actual OG image
        width: 1200,
        height: 630,
        alt: "Template builder",
      },
    ],
    locale: "en_US",
    type: "website",
  },
  metadataBase: new URL("https://my-template-builder.vercel.app/"),
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={roboto.className}>
      <body style={{ position: "relative" }}>
        <StyledComponentsRegistry>
          <StoreProvider>
            <Layout>
              <TanStackQueryProvider>{children}</TanStackQueryProvider>
            </Layout>
          </StoreProvider>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
